### PR TITLE
Object.assign

### PR DESCRIPTION
**Pull request by caub**
or maybe you care to support node 0.x ?

### CODE REVIEW

**Comment by vkarpov15** [comment]
Yeah one objective for v1.x is supporting node 0.10.x and 0.12.x. Is there a good reason to switch to `Object.assign()` here?

**Comment by caub** [comment]
I could add https://www.npmjs.com/package/object-assign or you can reject

**Comment by vkarpov15** [comment]
Yeah I'm going to reject unless there's a bug in the options copy code. No sense in breaking support for old versions of node or adding a new dependency unless there's some tangible benefit.

**Comment by caub** [comment]
yea np

you've got a mistake there https://github.com/mongodb-js/connect-mongodb-session/blob/master/index.js#L163 it should be `s`, next time you commit

**Comment by vkarpov15** [comment]
Hmm I don't see the bug, can you clarify?

**Pull request closed without merging**
